<?php
/**
 * Generated by bin/build-vendor.php — do not edit. Classmap autoloader for
 * the vendored, namespace-prefixed kilden/kilden-php core.
 */

$kilden_wp_classmap = array(
    'KildenWP\\Vendor\\Kilden\\Client' => __DIR__ . '/src/Client.php',
    'KildenWP\\Vendor\\Kilden\\FeatureFlags\\FlagCache' => __DIR__ . '/src/FeatureFlags/FlagCache.php',
    'KildenWP\\Vendor\\Kilden\\FeatureFlags\\Rollout' => __DIR__ . '/src/FeatureFlags/Rollout.php',
    'KildenWP\\Vendor\\Kilden\\IdentitySigner' => __DIR__ . '/src/IdentitySigner.php',
    'KildenWP\\Vendor\\Kilden\\Internal\\Json' => __DIR__ . '/src/Internal/Json.php',
    'KildenWP\\Vendor\\Kilden\\Internal\\Sender' => __DIR__ . '/src/Internal/Sender.php',
    'KildenWP\\Vendor\\Kilden\\Internal\\Timestamps' => __DIR__ . '/src/Internal/Timestamps.php',
    'KildenWP\\Vendor\\Kilden\\Internal\\Uuid' => __DIR__ . '/src/Internal/Uuid.php',
    'KildenWP\\Vendor\\Kilden\\Transport\\CurlTransport' => __DIR__ . '/src/Transport/CurlTransport.php',
    'KildenWP\\Vendor\\Kilden\\Transport\\StreamTransport' => __DIR__ . '/src/Transport/StreamTransport.php',
    'KildenWP\\Vendor\\Kilden\\Transport\\Transport' => __DIR__ . '/src/Transport/Transport.php',
    'KildenWP\\Vendor\\Kilden\\Transport\\TransportResponse' => __DIR__ . '/src/Transport/TransportResponse.php',
);

spl_autoload_register(static function ($class) use ($kilden_wp_classmap) {
    if (isset($kilden_wp_classmap[$class])) {
        require $kilden_wp_classmap[$class];
    }
});
